### ISSUE TITLE
When not properly exiting editable box in text_input.rb - arrow movement to the sides fails

### ISSUE THREAD

**Issue by Juksefantomet** [gosu/gosu-examples#11]
![arrow_sides_bug](https://user-images.githubusercontent.com/13452749/44628435-fe57c980-a93f-11e8-8b2b-3fa5db39b9a3.png)

When in text_input.rb

If you type in text into a text_field_box and proceed to click on another tutorial/example without exiting the box you cannot move to the sides in cptn_ruby.rb or tutorial.rb

**Comment by jlnr** [comment]
Good catch :)
