### ISSUE TITLE
Update gem

### ISSUE THREAD

**Issue by Chadowo** [gosu/gosu-examples#17]
I noticed that while using the gem version of this repository there's a font deprecation warning (#15), and bold text doesn't appear as such in the `welcome.rb` example. This however was fixed in commits ba3cf92 and ea550c7, but the latest version of this project (and the one on RubyGems) is v1.0.5. It would be nice to bump the version so the people that install from `gem` can get these changes. Thanks :smile:

**Comment by jlnr** [comment]
I have just pushed v1.0.7, thanks for nudging me.
