### ISSUE TITLE
Window is not centered because of dynamic resizing

### ISSUE THREAD

**Issue by jlnr** [gosu/gosu-examples#8]
Not sure what the ideal solution is, but right now the window can even be partially off-screen when first running the examples box.

**Comment by Juksefantomet** [comment]
i've only briefly looked at the code, but is the main window drawn and THEN the sidebar applied, or is the total width of both applied before it's drawn on the screen? i'm using a width/2 + heigth/2 and i'm always getting my window centered but i'm not applying a sidebar like your example + sidebar list is.

if your main window is drawn and then sidebar is applied then the original window is centered but would seem off when the sidebar gets slapped on 🤒

**Comment by jlnr** [comment]
If I remember correctly, the issue here is that window initially ONLY contains the sidebar. It is then centered, and then the initial example loads, and enlarges the window to the right.
